server:
  port: 8070
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

  application:
    name: dubbo-rest

---
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 192.168.1.30:8848

# Dubbo
dubbo:
  protocols:
    rest:
      name: rest
      port: 8090
      server: netty
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: nacos://192.168.1.30:8848
  consumer:
    timeout: 30000
    check: false
    retries: 0


