spring:
  profiles:
    active: dev

  application:
    name: dubbo-test

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      config:
        server-addr: localhost:8848

# Dubbo
dubbo:
  application:
    id: dubbo-test
    name: dubbo-test
    qos-enable: false
  registry:
    address: nacos://localhost:8848
  protocol:
    name: rest
    port: 8090
    server: netty

