server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: gateway01

  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

---
spring:
  cloud:
    # nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.1.30:8848

---
spring:
  cloud:
    sentinel:
      eager: true
      enabled: true
      transport:
        dashboard: 192.168.1.30:8080

---
spring:
  cloud:
    sentinel:
      enabled: true


---
spring:
  cloud:
    ## gateway配置
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true

      # 默认filter
      default-filters:
        # 添加网关标识
        - AddResponseHeader=X-Request-Gateway, ${spring.application.name}

      routes:
        - id: es-test2
          # uri: http://192.168.1.16:9200
          uri: lb://dubbo-rest
          # predicate断言，判断哪些请求需要代理
          predicates:
            - Path=/es/**
            - Method=GET,POST
          # filter过滤器
          filters:
            - SignatureValidate
            - RewritePath=/es/, /
            - ModifyRequest2=base64RewriteHandler, application/json
            - TokenValidate
            - ModifyResponse2=base64RewriteHandler, application/octet-stream



