spring:
  main:
    allow-bean-definition-overriding: true

---
spring:
  datasource:
    url: jdbc:mysql://192.168.1.30:3306/cloud-learn
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session

  redis:
    host: 192.168.1.30
    port: 6379
    password: yoostar403

