server:
  port: 8081
  servlet:
    session:
      timeout: 60m

spring:
  session:
    redis:
      flush-mode: on_save
      # redis key prefix
      namespace: spring:session

  redis:
    host: 192.168.1.30
    port: 6379
    password: yoostar403


