spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.1.30:9876

---
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: